In [45]:
# Code to normaize the rataing of the stock from the Yahoo Finance API
import pandas as pd
import os

In [46]:
# Store filepath in a variable
file_one = "yfapi_data.csv"

In [47]:
# Read our Data file with the pandas library
file_one_df = pd.read_csv(file_one, encoding="UTF-8")
file_one_df.head(5)

,Unnamed: 0,ticker,company_name,day_open,day_high,day_low,avg_analyst_rating,fifty_day_moving_avg,two_hundred_day_moving_avg
0,0,AAPL,Apple Inc.,167.99,172.6400,167.65,1.8 - Buy,166.3880,154.85630
1,1,GOOGL,Alphabet Inc.,2774.05,2791.7700,2757.01,1.7 - Buy,2693.1436,2742.93020
2,2,MSFT,Microsoft Corporation,300.51,303.2200,297.73,1.7 - Buy,297.7866,301.60526
3,3,AMZN,"Amazon.com, Inc.",3274.10,3326.5250,3253.74,1.7 - Buy,3036.9736,3331.57800
4,4,FB,"Meta Platforms, Inc.",213.33,216.7988,212.16,2.1 - Buy,245.4686,319.92676

In [48]:
file_one_df[['num_rating','rating']] = file_one_df['avg_analyst_rating'].str.split('-', expand=True)
file_one_df = file_one_df.drop('avg_analyst_rating', axis=1)

In [49]:
file_one_df.head()

,Unnamed: 0,ticker,company_name,day_open,day_high,day_low,fifty_day_moving_avg,two_hundred_day_moving_avg,num_rating,rating
0,0,AAPL,Apple Inc.,167.99,172.6400,167.65,166.3880,154.85630,1.8,Buy
1,1,GOOGL,Alphabet Inc.,2774.05,2791.7700,2757.01,2693.1436,2742.93020,1.7,Buy
2,2,MSFT,Microsoft Corporation,300.51,303.2200,297.73,297.7866,301.60526,1.7,Buy
3,3,AMZN,"Amazon.com, Inc.",3274.10,3326.5250,3253.74,3036.9736,3331.57800,1.7,Buy
4,4,FB,"Meta Platforms, Inc.",213.33,216.7988,212.16,245.4686,319.92676,2.1,Buy

In [50]:
file_one_df['norm_rating'] = ""
file_one_df.head()

,Unnamed: 0,ticker,company_name,day_open,day_high,day_low,fifty_day_moving_avg,two_hundred_day_moving_avg,num_rating,rating,norm_rating
0,0,AAPL,Apple Inc.,167.99,172.6400,167.65,166.3880,154.85630,1.8,Buy,
1,1,GOOGL,Alphabet Inc.,2774.05,2791.7700,2757.01,2693.1436,2742.93020,1.7,Buy,
2,2,MSFT,Microsoft Corporation,300.51,303.2200,297.73,297.7866,301.60526,1.7,Buy,
3,3,AMZN,"Amazon.com, Inc.",3274.10,3326.5250,3253.74,3036.9736,3331.57800,1.7,Buy,
4,4,FB,"Meta Platforms, Inc.",213.33,216.7988,212.16,245.4686,319.92676,2.1,Buy,

In [53]:
file_one_df['rating'] = file_one_df['rating'].str.strip()
file_one_df.head()

,Unnamed: 0,ticker,company_name,day_open,day_high,day_low,fifty_day_moving_avg,two_hundred_day_moving_avg,num_rating,rating,norm_rating
0,0,AAPL,Apple Inc.,167.99,172.6400,167.65,166.3880,154.85630,1.8,Buy,
1,1,GOOGL,Alphabet Inc.,2774.05,2791.7700,2757.01,2693.1436,2742.93020,1.7,Buy,
2,2,MSFT,Microsoft Corporation,300.51,303.2200,297.73,297.7866,301.60526,1.7,Buy,
3,3,AMZN,"Amazon.com, Inc.",3274.10,3326.5250,3253.74,3036.9736,3331.57800,1.7,Buy,
4,4,FB,"Meta Platforms, Inc.",213.33,216.7988,212.16,245.4686,319.92676,2.1,Buy,

In [54]:
for index, row in file_one_df.iterrows():
    rating = row['rating']

    if rating == 'Strong Buy':
        norm_rating = 5
    elif rating == 'Buy':
        norm_rating = 4
    elif rating == 'Hold':
        norm_rating = 3
    elif rating == 'Under Perform':
        norm_rating = 2
    else:
        norm_rating = 1 

    file_one_df.loc[index, 'norm_rating'] = norm_rating

file_one_df

,Unnamed: 0,ticker,company_name,day_open,day_high,day_low,fifty_day_moving_avg,two_hundred_day_moving_avg,num_rating,rating,norm_rating
0,0,AAPL,Apple Inc.,167.990,172.6400,167.6500,166.3880,154.85630,1.8,Buy,4
1,1,GOOGL,Alphabet Inc.,2774.050,2791.7700,2757.0100,2693.1436,2742.93020,1.7,Buy,4
2,2,MSFT,Microsoft Corporation,300.510,303.2200,297.7300,297.7866,301.60526,1.7,Buy,4
3,3,AMZN,"Amazon.com, Inc.",3274.100,3326.5250,3253.7400,3036.9736,3331.57800,1.7,Buy,4
4,4,FB,"Meta Platforms, Inc.",213.330,216.7988,212.1600,245.4686,319.92676,2.1,Buy,4
5,5,GOOG,Alphabet Inc.,2782.770,2800.5000,2763.3400,2695.3997,2765.66000,1.5,Strong Buy,5
6,6,TSLA,"Tesla, Inc.",979.940,1040.7000,976.7500,900.3418,854.58716,2.5,Buy,4
7,7,NVDA,NVIDIA Corporation,261.260,266.1150,255.7501,243.8352,238.35402,2.0,Buy,4
8,8,JPM,JP Morgan Chase & Co.,140.980,141.5850,139.1999,146.8884,156.77010,2.5,Buy,4
9,9,UNH,UnitedHealth Group Incorporated,502.270,507.0600,501.3348,478.1448,442.89334,1.9,Buy,4
10,10,JNJ,Johnson & Johnson,175.230,175.5400,174.0900,169.0054,167.50030,2.1,Buy,4
11,11,PG,Procter & Gamble Company (The),152.200,153.0100,150.6900,156.2470,147.41235,2.4,Buy,4
12,12,V,Visa Inc.,215.300,217.2850,214.2000,215.2774,222.92880,1.7,Buy,4
13,13,HD,"Home Depot, Inc. (The)",326.900,328.1900,315.8500,345.8964,349.85760,2.1,Buy,4
14,14,BAC,Bank of America Corporation,43.720,44.0100,43.0300,45.1530,43.43840,2.3,Buy,4
15,15,XOM,Exxon Mobil Corporation,83.340,84.2700,83.0500,78.0540,64.77270,2.5,Buy,4
16,16,MA,Mastercard Incorporated,343.400,346.7300,341.7500,359.0146,357.44540,1.8,Buy,4
17,17,DIS,Walt Disney Company (The),139.070,139.7600,137.5400,144.1144,163.59634,2.0,Buy,4
18,18,CVX,Chevron Corporation,166.000,167.3463,164.9400,142.3968,116.00470,2.2,Buy,4
19,19,ABBV,AbbVie Inc.,160.010,161.1800,158.3600,143.9914,123.45500,2.1,Buy,4
20,20,KO,Coca-Cola Company (The),60.750,60.9800,59.9950,60.7612,57.01060,2.1,Buy,4
21,21,CSCO,"Cisco Systems, Inc.",55.900,56.0900,54.4500,56.2980,56.38825,2.4,Buy,4
22,22,AVGO,Broadcom Inc.,608.000,611.3400,599.1600,584.0504,537.50793,1.9,Buy,4
23,23,COST,Costco Wholesale Corporation,556.950,560.6063,551.9600,516.3028,480.40850,2.2,Buy,4
24,24,PEP,"Pepsico, Inc.",164.248,165.2750,162.6600,167.5764,160.52610,2.4,Buy,4
25,25,VZ,Verizon Communications Inc.,51.050,51.4563,50.9600,53.1624,53.83680,2.7,Hold,3
26,26,ADBE,Adobe Inc.,437.510,437.9800,416.4700,481.0390,582.51670,1.8,Buy,4
27,27,TMO,Thermo Fisher Scientific Inc,581.600,583.0800,569.9500,568.5154,573.96000,1.8,Buy,4
28,28,ABT,Abbott Laboratories,121.110,121.2400,116.7350,123.4590,124.01855,2.0,Buy,4
29,29,CMCSA,Comcast Corporation,47.150,47.3500,46.5200,48.0834,53.43965,2.1,Buy,4
30,30,WFC,Wells Fargo & Company,52.760,53.0500,51.0950,53.9430,49.18300,2.0,Buy,4
31,31,CRM,Salesforce.com Inc,213.870,213.9300,208.3100,213.0898,251.00415,1.8,Buy,4
32,32,LLY,Eli Lilly and Company,284.420,288.1800,283.3500,252.4196,248.92995,2.0,Buy,4
33,33,INTC,Intel Corporation,48.460,49.5800,48.0601,48.9772,52.11470,2.9,Hold,3
34,34,WMT,Walmart Inc.,143.140,143.7300,141.5200,139.8566,142.39790,2.0,Buy,4
35,35,MRK,"Merck & Company, Inc.",79.300,80.5800,79.2300,78.5520,77.89430,2.2,Buy,4
36,36,AMD,"Advanced Micro Devices, Inc.",114.290,117.5400,112.2100,117.5262,115.73820,2.2,Buy,4
37,37,QCOM,QUALCOMM Incorporated,156.110,157.2100,152.5800,167.5698,154.74150,2.0,Buy,4
38,38,DHR,Danaher Corporation,291.320,291.3550,285.4300,278.9062,296.89206,1.8,Buy,4
39,39,NKE,"Nike, Inc.",132.640,135.4000,131.2000,139.1092,155.40704,2.1,Buy,4
40,40,T,AT&T Inc.,23.210,23.4500,23.1700,24.4608,26.04200,2.7,Hold,3
41,41,NFLX,"Netflix, Inc.",379.770,382.4600,374.4900,406.2238,539.34265,2.3,Buy,4
42,42,UNP,Union Pacific Corporation,265.060,269.7700,264.5200,249.6834,232.31870,2.0,Buy,4
43,43,PM,Philip Morris International Inc,92.720,93.1350,91.1600,101.3498,98.27800,2.3,Buy,4
44,44,LOW,"Lowe's Companies, Inc.",227.000,227.9500,219.8301,229.6676,219.84586,1.9,Buy,4
45,45,TXN,Texas Instruments Incorporated,182.000,183.0000,179.0400,174.0218,186.59296,2.5,Buy,4
46,46,ROKU,"Roku, Inc.",124.250,130.9000,122.5000,143.4742,280.59820,2.1,Buy,4

In [55]:
# Export file as a CSV, without the Pandas index, but with the header
output_path = os.path.join("yfapi_data_nrmal.csv")
file_one_df.to_csv(output_path, index=False, header=True)
print(output_path)

yfapi_data_nrmal.csv